### ISSUE TITLE
interpretation of ucr variable for sshd

### ISSUE THREAD

**Issue by fbim-genosr** [univention/ansible-modules#2]
I used to set some ucr variables with the ansible module in the form

 name: set ucr variables valid for all UCS Servers
  tags: ucrvars
  univention_config_registry:
    keys:
      sshd/permitroot: no
     ...

Setting the variable for a target host

sshd/permitroot: no

does set the variable to "False", instead of "no". That leads to **unsupported option** error in sshd, when restarting sshd.

Jul 19 08:52:23 groupware sshd[846]: /etc/ssh/sshd_config line 40: unsupported option "False".
Jul 19 08:52:23 groupware systemd[1]: ssh.service: Control process exited, code=exited status=255
Jul 19 08:52:23 groupware systemd[1]: ssh.service: Unit entered failed state.
Jul 19 08:52:23 groupware systemd[1]: ssh.service: Failed with result 'exit-code'.
Jul 19 08:52:23 groupware systemd[1]: ssh.service: Service hold-off time over, scheduling restart.

**Comment by pmhahn** [comment]
This is not a UCS bug, but [basic Ansible knowledge](https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html):
Ansible scripts are [YAML files](http://yaml.org/type/bool.html), which have their own syntax for boolean values:

Any string matching the following values
>  y|Y|yes|Yes|YES|n|N|no|No|NO
> |true|True|TRUE|false|False|FALSE
> |on|On|ON|off|Off|OFF

are parsed as boolean and converted to `True` and `False` **before** Ansible or any Ansible module like `ucr` has a chance to see the original value.
You **must** quote these strings in your initial YAML file to prevent this, e.g. 
```yaml
name: set ucr variables valid for all UCS Servers
tags: ucrvars
univention_config_registry:
  keys:
    sshd/permitroot: "no"
```
