### ISSUE TITLE
univention_directory_manager: Task status is never changed

### ISSUE THREAD

**Issue by Daenou** [univention/ansible-modules#6]
The UDM module doesn't appear to check if the state is already present on the machine, instead it executes the code either way every time you run the code, and reports the task as "ok", even though it should be "changed" as ansible actually modified something on the system.

Furthermore, this makes it impossible to see what actually has been changed on the system, did we have to create a completely new object, or did we just modify the description? Impossible to know currently.

**Comment by HunterZeroSix** [comment]
fixed in [feat(univention_directory_manager): implement change status](https://github.com/univention/ansible-modules/commit/fa965a56587b4dbba776b7458cfcbd4b5f255de9) 

* set the correct change status

Feel free to reopen or create a new issue if the error occurs again.
